# This is a basic workflow that is manually triggered

name: Performance Test Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      users:
        description: 'Number of concurrent users to test'
        default: '40'
        required: true
      hours:
        description: 'Duration of test'
        default: '24'
        required: true
      reportname:
        description: 'Valid reportname'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: bahmni-cluster-nonprod
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_AWS_ID }}
          aws-secret-access-key: ${{ secrets.BAHMNI_AWS_SECRET }}
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.BAHMNI_INFRA_ADMIN_ROLE }}
          role-duration-seconds: 1200  # 20 mins
          role-session-name: BahmniInfraAdminSession
    # Runs a single command using the runners shell
      - name: Start Performance Test AWS EC2
        run: |
          aws ec2 start-instances --instance-ids $(aws ec2 describe-instances --filters "Name=tag:Name,Values=performance-instance" --query "Reservations[].Instances[].InstanceId" --output text --region ap-south-1) --region ap-south-1
